// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://khxuqhtdklvpcdryxtwg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtoeHVxaHRka2x2cGNkcnl4dHdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0ODc4NjUsImV4cCI6MjA3NDA2Mzg2NX0.pVKTDGZFqeuTjpVjj1tezGJKj_NbyWgelQMX_pblh_0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});